server:
  port: 9192
spring:
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="xzp1rmgl" password="D3CDvEz_QNLtnpLkgxqBmAabWHwiLXO4";
    consumer:
      group-id: xzp1rmgl-consumers
      auto-offset-reset: latest
      properties.spring.json.trusted.packages: sample.kafka

  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
      function:
        definition: orderPurchaseEventPublisher;transactionEventProcessor;
      bindings:
        orderPurchaseEventPublisher-out-0:
          destination: xzp1rmgl-orders
        transactionEventProcessor-in-0:
          destination: xzp1rmgl-transactions
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true